Task 12.5
AdamPawlinski/ajax-12.5 pull request #1
Opened 2018-03-25 09:58 UTC by AdamPawlinski

Finish task 12.5. Ask for acceptance.

2018-03-25 20:50 UTC, matwjablonski requested changes

2018-03-25 20:50 UTC, matwjablonski commented on js/script.js
> +    var data = input[0];
you are taking first element from array input. from where you know that input is an array? check that input contain at least one element before you assign it to variable data

2018-03-27 04:43 UTC, AdamPawlinski commented
I added the Array.isArray method to check if input is really an array. Is that okey?

2018-03-27 07:11 UTC, matwjablonski requested changes

2018-03-27 07:11 UTC, matwjablonski commented on js/script.js
> +    if (Array.isArray(input) === true) {
you can write it using negation operator :) will be shorten

2018-03-27 21:36 UTC, AdamPawlinski commented
Is that okey?

2018-03-28 06:33 UTC, matwjablonski approved these changes

2018-09-12 04:11 UTC, merged